# Generated by Django 2.2.6 on 2019-11-03 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rso', '0001_initial'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rso.RSO'),
        ),
    ]
