# Generated by Django 2.2.6 on 2019-10-27 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='author',
            new_name='host',
        ),
    ]
