# Generated by Django 2.2.6 on 2019-11-03 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_rso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='rso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rso.RSO'),
        ),
    ]
