# Generated by Django 2.2.6 on 2019-11-19 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='coord',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.Place'),
        ),
    ]
