#!/bin/bash

echo "creating users"

python3 manage.py shell -c "from django.contrib.auth.models import User; user=User.objects.create_user('foo', password='bar', is_superuser=False, is_staff=False, email='0@knights.ucf.edu')"
python3 manage.py shell -c "from django.contrib.auth.models import User; user=User.objects.create_user('foo1', password='bar', is_superuser=False, is_staff=False, email='0@gmail.com')"
python3 manage.py shell -c "from django.contrib.auth.models import User; user=User.objects.create_user('foo2', password='bar', is_superuser=False, is_staff=False, email='2@knights.ucf.edu')"
python3 manage.py shell -c "from django.contrib.auth.models import User; user=User.objects.create_user('foo3', password='bar', is_superuser=False, is_staff=False, email='c3@knights.ucf.edu')"
python3 manage.py shell -c "from django.contrib.auth.models import User; user=User.objects.create_user('foo4', password='bar', is_superuser=False, is_staff=False, email='4@knights.ucf.edu')"
python3 manage.py shell -c "from django.contrib.auth.models import User; user=User.objects.create_user('foo5', password='bar', is_superuser=False, is_staff=False, email='5@knights.ucf.edu')"
python3 manage.py shell -c "from django.contrib.auth.models import User; user=User.objects.create_user('foo6', password='bar', is_superuser=False, is_staff=False, email='6@knights.ucf.edu')"
python3 manage.py shell -c "from django.contrib.auth.models import User; user=User.objects.create_user('foo7', password='bar', is_superuser=False, is_staff=False, email='7@knights.ucf.edu')"
python3 manage.py shell -c "from django.contrib.auth.models import User; user=User.objects.create_user('foo8', password='bar', is_superuser=False, is_staff=False, email='8@knights.ucf.edu')"
python3 manage.py shell -c "from django.contrib.auth.models import User; user=User.objects.create_user('foo9', password='bar', is_superuser=False, is_staff=False, email='9@knights.ucf.edu')"
python3 manage.py shell -c "from django.contrib.auth.models import User; user=User.objects.create_user('foo10', password='bar', is_superuser=False, is_staff=False, email='10@knights.ucf.edu')"
python3 manage.py shell -c "from django.contrib.auth.models import User; user=User.objects.create_user('foo11', password='bar', is_superuser=False, is_staff=False, email='11@knights.ucf.edu')"
python3 manage.py shell -c "from django.contrib.auth.models import User; user=User.objects.create_user('foo12', password='bar', is_superuser=False, is_staff=False, email='12@knights.ucf.edu')"
python3 manage.py shell -c "from django.contrib.auth.models import User; user=User.objects.create_user('foo13', password='bar', is_superuser=False, is_staff=False, email='13@knights.ucf.edu')"
python3 manage.py shell -c "from django.contrib.auth.models import User; user=User.objects.create_user('foo14', password='bar', is_superuser=False, is_staff=False, email='14@knights.ucf.edu')"
python3 manage.py shell -c "from django.contrib.auth.models import User; user=User.objects.create_user('foo15', password='bar', is_superuser=False, is_staff=False, email='15@knights.ucf.edu')"
python3 manage.py shell -c "from django.contrib.auth.models import User; user=User.objects.create_user('foo16', password='bar', is_superuser=False, is_staff=False, email='16@knights.ucf.edu')"
python3 manage.py shell -c "from django.contrib.auth.models import User; user=User.objects.create_user('foo17', password='bar', is_superuser=False, is_staff=False, email='17@knights.ucf.edu')"
python3 manage.py shell -c "from django.contrib.auth.models import User; user=User.objects.create_user('foo18', password='bar', is_superuser=False, is_staff=False, email='18@knights.ucf.edu')"
python3 manage.py shell -c "from django.contrib.auth.models import User; user=User.objects.create_user('foo19', password='bar', is_superuser=False, is_staff=False, email='19@knights.ucf.edu')"
python3 manage.py shell -c "from django.contrib.auth.models import User; user=User.objects.create_user('foo20', password='bar', is_superuser=False, is_staff=False, email='20@knights.ucf.edu')"
